version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: suntrack-db
    environment:
      POSTGRES_USER: suntrack
      POSTGRES_PASSWORD: suntrack
      POSTGRES_DB: suntrack
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U suntrack"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: suntrack-api
    ports:
      - "3000:3000"
    volumes:
      - ./api:/app
      - /app/node_modules
    environment:
      - DATABASE_URL=postgresql://suntrack:suntrack@postgres:5432/suntrack
      - NODE_ENV=development
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data: 